### ISSUE TITLE
cannot run template from fixel-tools

### ISSUE THREAD

**Issue by srukle** [HaxeFlixel/flixel-tools#56]
$ flixel tpl -n "FlixelTut"
$ cd FlixelTut
$ lime test -debug "Project.xml" linux
source/Main.hx:13: characters 23-28 : Unknown identifier : WIDTH
source/Main.hx:14: characters 24-30 : Unknown identifier : HEIGHT

Following these instructions:
http://haxeflixel.com/documentation/part-ii-testing/

---

This has been tested on two machines. Both machines failed. Further notes: http://sam.ruzek-klein.com/blog/development/fixel-tools-issue-on-debian-8-xfce4/

**Comment by jahndis** [comment]
I was experiencing the same issue and decided to dig into it a bit. It looks like this will only happen if using option 3 when setting up flixel-tools (in the IDE selection). Option 3 sets your IDE to "None". Currently there is not any templating that needs to happen (since there isn't a project file specific to the "None" IDE ;) ). However, the code is currently falsely assuming that if there isn't an IDE project template, that no replacements need to be made at all. However, the Main.hx.tpl and Project.xml.tpl file (at least) still need the substitutions. Also, if people create their own custom templates, they'd run into this issue when using the "None" IDE.

I think I might take a stab at fixing this. But, for now, a quick fix (I think) would be to run 'haxelib run flixel-tools setup' and select any of the IDE's except "None", and then just delete the project file that gets generated when creating the template.

Hope this helps.

**Comment by jahndis** [comment]
Just for information's sake, what versions of everything are you using? (output of 'haxelib list') It appears this issue exists both in the dev branch, and in the latest release (1.1.0), but not in the previous release... I think this fix is going to be a one liner.
